# Generated by Django 4.2.2 on 2023-06-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='nam',
        ),
    ]
