# Generated by Django 4.2.2 on 2023-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nam',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
